#!/usr/bin/env sh
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT/npm test --if-present" && pnpm exec tsc --noEmit 2>/dev/null  || exit 1
cd "$ROOT/npm test --if-present" &&  npm run typecheck --if-present || exit 1
